In [4]:
import numpy as np
import time
import sys

In [5]:
l = range(1000)

In [6]:
# get the size of first element and multiply by its len
print(sys.getsizeof(5)*len(l))

28000


In [7]:
array = np.arange(1000)

print(array.size*array.itemsize)


4000


# in the above step we compare the memory used by list and numpy

In [17]:
# we check the who is faster numpy or list

SIZE = 1000000

l1 = range(SIZE)
l2 = range(SIZE)


ar1 = np.arange(SIZE)
ar2 = np.arange(SIZE)

# adding list 
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("the time taken by list is :",(time.time()-start)*SIZE)

# use numpy
start = time.time()
result = ar1 +ar2
print("Time taken by Numpy :",(time.time()-start)*SIZE)



the time taken by list is : 358435.86921691895
Time taken by Numpy : 46870.47004699707


In [4]:
# to inintialized numpy with default value we use np.ones or zeroes

import numpy as np
np.ones((3,4),dtype=np.int32)


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# use of linspace()
- This is useful to create linear sequence

In [14]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])


# change the shape of array
- shape() give the actual shape
- reshape() give the reshape after chage but not change original
- ravel to create one dimenshion array

In [32]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
a.shape


(3, 2)

In [34]:
# her we change the shape or array
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [36]:
# to create one dimenshional array we use ravel
b =a.ravel()

In [38]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

# make some operation
- min give minimum value
- max give maximum value
- sum give sum of element
- sum(axis = 0) give the sum of indivisuals column (12,17) if we have 2 column
- sum(axis = 1) give the sum of indivisuals row (2,4,5) if we have three row
- sqrt() this will give the square root of your given matrix

In [47]:
a = np.array([[1,2],[3,14],[5,6]])
a.dtype


dtype('int32')

In [48]:
# to find minimum value
a.min()

1

In [49]:
# to find maximum values
a.max()

14

In [56]:
# to find sum of elemnt
a.sum()

31

In [59]:
a.sum(axis=0)

array([ 9, 22])

In [60]:
a.sum(axis=1)

array([ 3, 17, 11])

In [57]:
np.square(a)

array([[  1,   4],
       [  9, 196],
       [ 25,  36]], dtype=int32)

In [58]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 3.74165739],
       [2.23606798, 2.44948974]])

# Do some mathmatical operation in two matrix
- "+" add two matrix
- "-" subtract two matrix
- "*" to multiple two matrix
- "/" to divide two matrix
- dot to find the product of two matrix

In [85]:
one = np.array([[1,2],[67,12],[4,5]])
sec = np.array([[12,34],[6,9],[7,8]])
one


array([[ 1,  2],
       [67, 12],
       [ 4,  5]])

In [93]:
sec

array([[12, 34],
       [ 6,  9],
       [ 7,  8]])

In [94]:
#one-sec

In [95]:
one+sec

array([[13, 36],
       [73, 21],
       [11, 13]])

In [96]:
one*sec

array([[ 12,  68],
       [402, 108],
       [ 28,  40]])

In [97]:
one/sec

array([[ 0.08333333,  0.05882353],
       [11.16666667,  1.33333333],
       [ 0.57142857,  0.625     ]])

In [98]:
np.dot(b,a)

ValueError: shapes (6,) and (3,2) not aligned: 6 (dim 0) != 3 (dim 0)