In [1]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)


[10 20 30 40 50]


# creating array in numpy can be done in several ways.
- using array() function
- using linspace() function
- using logspace() function
- using arrange() function
- using arrange() function
- using zeros() and ones() functions

In [2]:
# creating array using linspace
from numpy import *
a = linspace(0,10,6).reshape(3,2)
print('a = ',a)
    

a =  [[ 0.  2.]
 [ 4.  6.]
 [ 8. 10.]]


In [3]:
# creating using logspace
a = logspace(1,4,5)
a
for i in a:
    print(i,end=" ")

10.0 56.23413251903491 316.22776601683796 1778.2794100389228 10000.0 

In [4]:
# creating array using arange()
a = arange(2,13,2).reshape(2,3)
print(a)

[[ 2  4  6]
 [ 8 10 12]]


In [5]:

# creating array with default value zeros, ones 
a = zeros((3,3),int)
b = ones(5)
print("A : ",a)
print("B :",b)

A :  [[0 0 0]
 [0 0 0]
 [0 0 0]]
B : [1. 1. 1. 1. 1.]


In [6]:
#Mathematical operations on array
# import all from numpy module
from numpy import *
arr = array([10,20,30,40,50])
print("oringinal array       :",arr)

# do mathematical operation
print("After adding 5        :",arr+5)
print("After subtracting 5   :",arr-5)
print("After multiply with 5 : ",arr*5)
print("After dividing with 5 :",arr/5)
print("After modulus witht 5 :",arr%5)

print("Expression values :",(arr+5)**2-10)

# do some  math function
print("Sin value :", sin(arr))
print("cos value : ",cos(arr))
print("tan values : ",tan(arr))
print("Biggest element :",max(arr))
print("smallest element :",min(arr))
print("sum pf all element :",sum(arr))
print("Average of all elements :",mean(arr))



oringinal array       : [10 20 30 40 50]
After adding 5        : [15 25 35 45 55]
After subtracting 5   : [ 5 15 25 35 45]
After multiply with 5 :  [ 50 100 150 200 250]
After dividing with 5 : [ 2.  4.  6.  8. 10.]
After modulus witht 5 : [0 0 0 0 0]
Expression values : [ 215  615 1215 2015 3015]
Sin value : [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
cos value :  [-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
tan values :  [ 0.64836083  2.23716094 -6.4053312  -1.11721493 -0.27190061]
Biggest element : 50
smallest element : 10
sum pf all element : 150
Average of all elements : 30.0


## usng all() and any() function2
- all() function can be used to determine whether all the elements in the array and True
- any() function can be used to determine if any one element of the array is True.

In [7]:
# using any() an all()

a = array([1,2,3,0,4,0])
b = array([0,5,6,7,1,2])

c = a>b
print("Result of a>b",c)

print("check if any one element is true :",any(c))
print("check if all elements are true :",all(c))


Result of a>b [ True False False False  True False]
check if any one element is true : True
check if all elements are true : False


# 
## Attributes of an array
- ndim attribute
- shape attribute
- size attribute
- itemsize attribute
- dtype attribute
- nbyte attribute
- reshape() method
- flaten() method


## Attributes of an array
- ndim attribute
- shape attribute
- size attribute
- itemsize attribute
- dtype attribute
- nbyte attribute
- reshape() method
- flaten() method


In [8]:
from numpy import *
arr = array([10,20,30,40,50,60,68,80])
arr2 = array([[12,34,56],[23,56,58]])

print("use of ndim :",arr.ndim)
print("use od ndim :",arr2.ndim)

print("use of shape :",arr2.shape)
print("use of size :",arr.size)
print("use of itemsize :", arr.itemsize)
print("use of dtype :",arr.dtype)
print("use of nbytes :",arr.nbytes)
print("use of reshape :",arr.reshape(4,2))

print("use of flatten :",arr.flatten())

use of ndim : 1
use od ndim : 2
use of shape : (2, 3)
use of size : 8
use of itemsize : 4
use of dtype : int32
use of nbytes : 32
use of reshape : [[10 20]
 [30 40]
 [50 60]
 [68 80]]
use of flatten : [10 20 30 40 50 60 68 80]
