In [1]:
import numpy as np


np.random.random((2,5))

array([[0.30057355, 0.62233986, 0.40169805, 0.3466457 , 0.95936942],
       [0.76779576, 0.05758801, 0.31389126, 0.61504551, 0.78074555]])

In [2]:
# 100 values between 1 vand 50
a = np.linspace(0,2,50)
a

array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
       0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
       0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
       0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
       0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
       1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
       1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
       1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
       1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
       1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ])

In [3]:
a = np.arange(8)

In [66]:
a.reshape(2,4)

array([[ 1,  2,  3,  9],
       [ 4,  5,  6, 12]])

In [5]:
np.arange(15).reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# accessing Numpy array element

In [6]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [7]:
a[1:4]

array([2, 3, 4])

In [78]:

# two dimension

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [84]:
# use of steps
a[::2,::2]

array([[1, 3],
       [7, 9]])

In [81]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
a>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
# to print value
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.where(a>2)
# first will show row index
# second will show column index


(array([0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [15]:
a[(a>2)&(a<5)]

array([3, 4])

In [16]:
x = np.where(a>4)

In [17]:
x

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [18]:
# to print value in row column
for i,k in zip(x[0],x[1]):
    print(a[i,k],":",i,k)

5 : 1 1
6 : 1 2
7 : 2 0
8 : 2 1
9 : 2 2


# subset

In [19]:
a = np.arange(10)


In [20]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b = a

In [22]:
b[0] = 121

In [23]:
a

array([121,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [24]:
b

array([121,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [25]:
# to check memory

np.shares_memory(a,b)

True

In [26]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# create copy of array or arange

b = a.copy()

In [28]:
np.shares_memory(a,b)

False

In [29]:
b[0]= 111

In [30]:
b

array([111,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [31]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## more option

In [32]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
b = np.array([[0,1,2],[10,11,12]])
b

array([[ 0,  1,  2],
       [10, 11, 12]])

In [35]:
# use of dot 
np.dot(a,b.T)

array([[  8,  68],
       [ 17, 167]])

In [36]:
# maths operations
#b+2

#-2
#**2
b


array([[ 0,  1,  2],
       [10, 11, 12]])

In [37]:
a == b

array([[False, False, False],
       [False, False, False]])

In [38]:
b[a==b]

array([], dtype=int32)

In [39]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
b

array([[ 0,  1,  2],
       [10, 11, 12]])

In [41]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  1,  2],
       [10, 11, 12]])

In [42]:
np.concatenate((b,a),axis =0)

array([[ 0,  1,  2],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [43]:
np.hstack((a,b))

array([[ 1,  2,  3,  0,  1,  2],
       [ 4,  5,  6, 10, 11, 12]])

In [44]:
np.sum(a)

21

In [72]:
np.median(a)

4.5

In [71]:
np.mean(a)

5.25

In [47]:
a = np.array([1,1,0],dtype=bool)
b = np.array([1,0,1],dtype=bool)
a

array([ True,  True, False])

In [48]:
b

array([ True, False,  True])

In [49]:
np.logical_and(a,b)

array([ True, False, False])

In [50]:
np.logical_or(a,b)

array([ True,  True,  True])

In [51]:
np.logical_not(a,b)

array([False, False,  True])

In [52]:

a = b

In [53]:
b

array([False, False,  True])

In [54]:
a = np.array([[1,2,3,9],[4,5,6,12]])

In [55]:
a

array([[ 1,  2,  3,  9],
       [ 4,  5,  6, 12]])

In [56]:
b= a

In [57]:
np.all(a= b)

True

In [58]:
a

array([[ 1,  2,  3,  9],
       [ 4,  5,  6, 12]])

In [59]:
a.sum()

42

In [60]:
# axis 0 is used for  column
# axis 1 is used for  row
a.sum(axis= 0)

array([ 5,  7,  9, 21])

In [61]:
a.sum(axis = 1)

array([15, 27])

In [62]:
a.max()

12

In [63]:
a.argmax()

7

In [64]:
a

array([[ 1,  2,  3,  9],
       [ 4,  5,  6, 12]])