## Multiple Linear Regression

### Multiple regression is to learn more about the relationship between several independent variables and a dependent variable.

<img src='images/multiple_reg.PNG' />

In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### importing dataset

In [59]:
##Linear regression

In [60]:
data = pd.read_csv('dataset/50_Startups.csv')
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [61]:
data.dtypes

R&D Spend          float64
Administration     float64
Marketing Spend    float64
State               object
Profit             float64
dtype: object

In [62]:
#nomial features  ( one hot encoding)
#ordinal features (label ending)

In [63]:
data.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [64]:
d=pd.get_dummies(data['State'])

In [65]:
d.head()

California  Florida  New York
0           0        0         1
1           1        0         0
2           0        1         0
3           0        0         1
4           0        1         0

In [66]:
#data.iloc[:,:-1].select_dtypes(exclude=['object'])

In [67]:
f=data.iloc[:,:-1].select_dtypes(exclude=['object'])
f.head()

R&D Spend  Administration  Marketing Spend
0  165349.20       136897.80        471784.10
1  162597.70       151377.59        443898.53
2  153441.51       101145.55        407934.54
3  144372.41       118671.85        383199.62
4  142107.34        91391.77        366168.42

In [68]:
f.head()

R&D Spend  Administration  Marketing Spend
0  165349.20       136897.80        471784.10
1  162597.70       151377.59        443898.53
2  153441.51       101145.55        407934.54
3  144372.41       118671.85        383199.62
4  142107.34        91391.77        366168.42

In [69]:
X=pd.concat((f,d),axis=1).values
#X

In [70]:
y=data['Profit'].values

In [71]:
X.shape

(50, 6)

In [72]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [73]:
from sklearn.preprocessing import LabelBinarizer

In [74]:
lab=LabelBinarizer()

In [100]:
m=lab.fit_transform(data['State'])


In [102]:
#lab.classes_

In [77]:
pd.DataFrame(m,columns=lab.classes_).head()
#lab.classes_

California  Florida  New York
0           0        0         1
1           1        0         0
2           0        1         0
3           0        0         1
4           0        1         0

### Split dataset

In [78]:
X.shape

(50, 6)

In [79]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=10,
                                                 random_state=10)

In [80]:
#X_test

In [81]:
#X_train.shape

In [82]:
print (X_train.shape)
X_test.shape

(40, 6)


(10, 6)

In [83]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [84]:
reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [85]:
reg.coef_

array([ 8.05859453e-01, -1.79706621e-02,  2.28153524e-02,  8.41023126e+01,
        6.95447747e+02, -7.79550060e+02])

In [86]:
reg.intercept_

50001.736040302574

In [104]:
X_test[0]

array([4.4069950e+04, 5.1283140e+04, 1.9702942e+05, 1.0000000e+00,
       0.0000000e+00, 0.0000000e+00])

In [88]:
#X_test[0].reshape(1,-1)

In [89]:
test=X_test[0].reshape(1,-1)

In [90]:
test.shape

(1, 6)

In [91]:
coff=reg.coef_.reshape(1,-1).T

In [92]:
coff.shape

(6, 1)

In [93]:
# formula to implement multiple regression

np.dot(test,coff)+reg.intercept_

array([[89173.72784099]])

In [94]:
y_pred = reg.predict(X_test)

In [95]:
y_pred[0]

89173.72784098808

In [96]:
y_test[0]

89949.14

In [97]:
r2_score(y_test,y_pred)

0.9901105113396005